services:
  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready", "-p", "5432", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 2s
    ports:
      - "5432:5432"
